# Generated by Django 3.0.7 on 2020-07-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_buying'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying',
            name='username',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
