# Generated by Django 3.0.7 on 2020-07-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_buying_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buying',
            old_name='username',
            new_name='uname',
        ),
    ]
