# Generated by Django 3.0.7 on 2020-07-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_buying_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
