# Generated by Django 3.0.7 on 2020-07-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying',
            name='phone_number',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
