# Generated by Django 3.0.7 on 2020-07-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postnewsfeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='posts')),
                ('caption', models.TextField()),
            ],
        ),
    ]
