# Generated by Django 3.0.7 on 2020-07-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_postnewsfeed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postnewsfeed',
        ),
    ]
