# Generated by Django 3.0.7 on 2020-07-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_postnewsfeed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
