# Generated by Django 3.0.7 on 2020-07-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='post_img',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
